# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import device_backend_pb2 as device__backend__pb2


class DeviceBackendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Capabilities = channel.unary_unary(
                '/reconfig_net.ocs.backend.v1.DeviceBackend/Capabilities',
                request_serializer=device__backend__pb2.Empty.SerializeToString,
                response_deserializer=device__backend__pb2.BackendCapabilities.FromString,
                )
        self.ReadEntries = channel.unary_unary(
                '/reconfig_net.ocs.backend.v1.DeviceBackend/ReadEntries',
                request_serializer=device__backend__pb2.Empty.SerializeToString,
                response_deserializer=device__backend__pb2.ReadEntriesResponse.FromString,
                )
        self.ApplyTransition = channel.unary_unary(
                '/reconfig_net.ocs.backend.v1.DeviceBackend/ApplyTransition',
                request_serializer=device__backend__pb2.ApplyTransitionRequest.SerializeToString,
                response_deserializer=device__backend__pb2.ApplyTransitionResponse.FromString,
                )
        self.Reconcile = channel.unary_unary(
                '/reconfig_net.ocs.backend.v1.DeviceBackend/Reconcile',
                request_serializer=device__backend__pb2.ReconcileRequest.SerializeToString,
                response_deserializer=device__backend__pb2.ReadEntriesResponse.FromString,
                )
        self.Recover = channel.unary_unary(
                '/reconfig_net.ocs.backend.v1.DeviceBackend/Recover',
                request_serializer=device__backend__pb2.RecoverRequest.SerializeToString,
                response_deserializer=device__backend__pb2.ApplyTransitionResponse.FromString,
                )


class DeviceBackendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Capabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyTransition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceBackendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.Capabilities,
                    request_deserializer=device__backend__pb2.Empty.FromString,
                    response_serializer=device__backend__pb2.BackendCapabilities.SerializeToString,
            ),
            'ReadEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadEntries,
                    request_deserializer=device__backend__pb2.Empty.FromString,
                    response_serializer=device__backend__pb2.ReadEntriesResponse.SerializeToString,
            ),
            'ApplyTransition': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyTransition,
                    request_deserializer=device__backend__pb2.ApplyTransitionRequest.FromString,
                    response_serializer=device__backend__pb2.ApplyTransitionResponse.SerializeToString,
            ),
            'Reconcile': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=device__backend__pb2.ReconcileRequest.FromString,
                    response_serializer=device__backend__pb2.ReadEntriesResponse.SerializeToString,
            ),
            'Recover': grpc.unary_unary_rpc_method_handler(
                    servicer.Recover,
                    request_deserializer=device__backend__pb2.RecoverRequest.FromString,
                    response_serializer=device__backend__pb2.ApplyTransitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reconfig_net.ocs.backend.v1.DeviceBackend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceBackend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.backend.v1.DeviceBackend/Capabilities',
            device__backend__pb2.Empty.SerializeToString,
            device__backend__pb2.BackendCapabilities.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.backend.v1.DeviceBackend/ReadEntries',
            device__backend__pb2.Empty.SerializeToString,
            device__backend__pb2.ReadEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyTransition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.backend.v1.DeviceBackend/ApplyTransition',
            device__backend__pb2.ApplyTransitionRequest.SerializeToString,
            device__backend__pb2.ApplyTransitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.backend.v1.DeviceBackend/Reconcile',
            device__backend__pb2.ReconcileRequest.SerializeToString,
            device__backend__pb2.ReadEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.backend.v1.DeviceBackend/Recover',
            device__backend__pb2.RecoverRequest.SerializeToString,
            device__backend__pb2.ApplyTransitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
