# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ocs_operations_pb2 as ocs__operations__pb2


class OcsOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireControl = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/AcquireControl',
                request_serializer=ocs__operations__pb2.AcquireControlRequest.SerializeToString,
                response_deserializer=ocs__operations__pb2.ControlLease.FromString,
                )
        self.RenewControl = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/RenewControl',
                request_serializer=ocs__operations__pb2.RenewControlRequest.SerializeToString,
                response_deserializer=ocs__operations__pb2.ControlLease.FromString,
                )
        self.ReleaseControl = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/ReleaseControl',
                request_serializer=ocs__operations__pb2.ReleaseControlRequest.SerializeToString,
                response_deserializer=ocs__operations__pb2.ControlState.FromString,
                )
        self.GetControlState = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/GetControlState',
                request_serializer=ocs__operations__pb2.Empty.SerializeToString,
                response_deserializer=ocs__operations__pb2.ControlState.FromString,
                )
        self.GetRuntime = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/GetRuntime',
                request_serializer=ocs__operations__pb2.Empty.SerializeToString,
                response_deserializer=ocs__operations__pb2.GetRuntimeResponse.FromString,
                )
        self.GetPermutation = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/GetPermutation',
                request_serializer=ocs__operations__pb2.Empty.SerializeToString,
                response_deserializer=ocs__operations__pb2.GetPermutationResponse.FromString,
                )
        self.ApplyBatch = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/ApplyBatch',
                request_serializer=ocs__operations__pb2.ApplyBatchRequest.SerializeToString,
                response_deserializer=ocs__operations__pb2.OperationReply.FromString,
                )
        self.SetMode = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/SetMode',
                request_serializer=ocs__operations__pb2.SetModeRequest.SerializeToString,
                response_deserializer=ocs__operations__pb2.OperationReply.FromString,
                )
        self.RecoverDeviceState = channel.unary_unary(
                '/reconfig_net.ocs.v1.OcsOperations/RecoverDeviceState',
                request_serializer=ocs__operations__pb2.RecoverDeviceStateRequest.SerializeToString,
                response_deserializer=ocs__operations__pb2.OperationReply.FromString,
                )


class OcsOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AcquireControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPermutation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverDeviceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OcsOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireControl': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireControl,
                    request_deserializer=ocs__operations__pb2.AcquireControlRequest.FromString,
                    response_serializer=ocs__operations__pb2.ControlLease.SerializeToString,
            ),
            'RenewControl': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewControl,
                    request_deserializer=ocs__operations__pb2.RenewControlRequest.FromString,
                    response_serializer=ocs__operations__pb2.ControlLease.SerializeToString,
            ),
            'ReleaseControl': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseControl,
                    request_deserializer=ocs__operations__pb2.ReleaseControlRequest.FromString,
                    response_serializer=ocs__operations__pb2.ControlState.SerializeToString,
            ),
            'GetControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlState,
                    request_deserializer=ocs__operations__pb2.Empty.FromString,
                    response_serializer=ocs__operations__pb2.ControlState.SerializeToString,
            ),
            'GetRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntime,
                    request_deserializer=ocs__operations__pb2.Empty.FromString,
                    response_serializer=ocs__operations__pb2.GetRuntimeResponse.SerializeToString,
            ),
            'GetPermutation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPermutation,
                    request_deserializer=ocs__operations__pb2.Empty.FromString,
                    response_serializer=ocs__operations__pb2.GetPermutationResponse.SerializeToString,
            ),
            'ApplyBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyBatch,
                    request_deserializer=ocs__operations__pb2.ApplyBatchRequest.FromString,
                    response_serializer=ocs__operations__pb2.OperationReply.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=ocs__operations__pb2.SetModeRequest.FromString,
                    response_serializer=ocs__operations__pb2.OperationReply.SerializeToString,
            ),
            'RecoverDeviceState': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverDeviceState,
                    request_deserializer=ocs__operations__pb2.RecoverDeviceStateRequest.FromString,
                    response_serializer=ocs__operations__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reconfig_net.ocs.v1.OcsOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OcsOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcquireControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/AcquireControl',
            ocs__operations__pb2.AcquireControlRequest.SerializeToString,
            ocs__operations__pb2.ControlLease.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenewControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/RenewControl',
            ocs__operations__pb2.RenewControlRequest.SerializeToString,
            ocs__operations__pb2.ControlLease.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/ReleaseControl',
            ocs__operations__pb2.ReleaseControlRequest.SerializeToString,
            ocs__operations__pb2.ControlState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/GetControlState',
            ocs__operations__pb2.Empty.SerializeToString,
            ocs__operations__pb2.ControlState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/GetRuntime',
            ocs__operations__pb2.Empty.SerializeToString,
            ocs__operations__pb2.GetRuntimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPermutation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/GetPermutation',
            ocs__operations__pb2.Empty.SerializeToString,
            ocs__operations__pb2.GetPermutationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/ApplyBatch',
            ocs__operations__pb2.ApplyBatchRequest.SerializeToString,
            ocs__operations__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/SetMode',
            ocs__operations__pb2.SetModeRequest.SerializeToString,
            ocs__operations__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecoverDeviceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reconfig_net.ocs.v1.OcsOperations/RecoverDeviceState',
            ocs__operations__pb2.RecoverDeviceStateRequest.SerializeToString,
            ocs__operations__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
