profile: p4app-v1
capability-profile: p4app-capabilities.yaml

openconfig-platform:components:
  component:
    - name: port-1
      index: 1
    - name: port-2
      index: 2
    - name: port-3
      index: 3
    - name: port-4
      index: 4
    - name: port-5
      index: 5
    - name: port-6
      index: 6
    - name: port-7
      index: 7
    - name: port-8
      index: 8

oc-optical-switch-connections:optical-switch-connections:
  port-connection:
    - connection-name: conn-port-1-port-2
      config:
        connection-name: conn-port-1-port-2
        bidirectional: true
        near-port-name: port-1
        far-port-name: port-2
    - connection-name: conn-port-3-port-4
      config:
        connection-name: conn-port-3-port-4
        bidirectional: true
        near-port-name: port-3
        far-port-name: port-4
    - connection-name: conn-port-5-port-6
      config:
        connection-name: conn-port-5-port-6
        bidirectional: true
        near-port-name: port-5
        far-port-name: port-6
    - connection-name: conn-port-7-port-8
      config:
        connection-name: conn-port-7-port-8
        bidirectional: true
        near-port-name: port-7
        far-port-name: port-8
