# p4app.json is the configuration file for the p4app
# p4app.json "default-target" can choose from ["demo-1", "demo-2"]

ll: compile
run:
	../p4app-main/p4app run .

compile:
	../p4app-main/p4app run . compile
